### PR TITLE
Mark enum as nullable for null enum members

### LINKED ISSUE #1030: Enum with null member crashes
### What version of `kubb` is running?

2.19.5

### What platform is your computer?

Mac

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

_No response_

### What steps can reproduce the bug?

A enum with a member of `null` causes a crash. You can see it in action in the [playground](https://kubb.dev/playground) by pasting in the document below. To be clear, I want null as in the null type, not a string of the text "null".

### How often does this bug happen?

Every time

### What is the expected behavior?

My understanding is that [this is the correct way to model a nullable enum](https://swagger.io/docs/specification/data-models/enums/). I know that kubb will make a nullable enum if you set the type to null (eg `type: [string, "null"]`), but I am also using another OpenAPI tool that works a differently and right now these two tools are fighting each other. It seems like kubb is the right place to fix this since it's not adhering to the spec.

### Swagger/OpenAPI file?

```yaml
openapi: 3.1.0

components:
  schemas:
    Enum:
      enum:
        - a
        - b
        - c
        - null
```

### Additional information

Running locally, I get this error:

```
[8:34:31 PM]  ERROR  Cannot read properties of null (reading 'toString') (plugin: plugin-zod, hook: buildStart) (plugin: plugin-zod, hook: buildStart)

  at EventEmitter.<anonymous> (/home/apps/node_modules/.pnpm/@kubb+core@2.19.5/node_modules/@kubb/core/src/logger.ts:74:19)
  at EventEmitter.emit (node:events:518:28)
  at EventEmitter.emit (/home/apps/node_modules/.pnpm/@kubb+core@2.19.5/node_modules/@kubb/core/src/utils/EventEmitter.ts:10:19)
  at Object.emit (/home/apps/node_modules/.pnpm/@kubb+core@2.19.5/node_modules/@kubb/core/src/logger.ts:89:21)
  at PluginManager.catcher_fn (/home/apps/node_modules/.pnpm/@kubb+core@2.19.5/node_modules/@kubb/core/src/PluginManager.ts:620:17)
  at /home/apps/node_modules/.pnpm/@kubb+core@2.19.5/node_modules/@kubb/core/src/PluginManager.ts:366:9
  at Array.forEach (<anonymous>)
  at PluginManager.hookParallel (/home/apps/node_modules/.pnpm/@kubb+core@2.19.5/node_modules/@kubb/core/src/PluginManager.ts:362:13)
  at safeBuild (/home/apps/node_modules/.pnpm/@kubb+core@2.19.5/node_modules/@kubb/core/src/build.ts:208:5)
  at generate (/home/apps/node_modules/.pnpm/@kubb+cli@2.19.5_typescript@5.4.5/node_modules/@kubb/cli/src/generate.ts:79:36)
```

### PR DESCRIPTION
**Pull request by aburgel**
Fixes #1030 

According to the [3.0 docs](https://swagger.io/docs/specification/data-models/enums/) and [this FAQ](https://github.com/OAI/OpenAPI-Specification/blob/main/proposals/2019-10-31-Clarify-Nullable.md#if-a-schema-specifies-nullable-true-and-enum-1-2-3-does-that-schema-allow-null-values-see-1900), an enum is nullable when both it's type is nullable and when null is a member of the enum. Currently kubb will crash with a null member, so this PR fixes this case.

I added a couple of test cases as well, but let me know if there are more ways I should test this.

### CODE REVIEW

File: packages/plugin-oas/src/SchemaGenerator.ts [hunk 1]
```diff
@@ -560,6 +560,12 @@ export abstract class SchemaGenerator<
         type: 'type',
       })
 
+      const nullableEnum = schema.enum.includes(null);
+      if (nullableEnum) {
+        baseItems.push({ keyword: schemaKeywords.nullable })
+      }
+      const filteredValues = schema.enum.filter((value) => value !== null);
```
Comment (aburgel) [inline packages/plugin-oas/src/SchemaGenerator.ts:567]: This is the fix. If `null` is one of the enum members, then the whole enum should be consider nullable. But we don't want `null` as one of the members, since that's not how Typescript works, so I filter it out.

File: packages/plugin-oas/src/SchemaGenerator.ts [hunk 2]
```diff
@@ -560,6 +560,12 @@ export abstract class SchemaGenerator<
...
+
       // x-enumNames has priority
       const extensionEnums = ['x-enumNames', 'x-enum-varnames']
```
Comment (aburgel) [inline packages/plugin-oas/src/SchemaGenerator.ts:570]: I wasn't sure if I should use the filtered values in this case. Any thoughts on how to handle this?

File: packages/swagger-ts/mocks/enums.yaml [hunk 3]
```diff
@@ -1,91 +1,105 @@
-
-definitions:
```
Comment (aburgel) [inline packages/swagger-ts/mocks/enums.yaml:2]: I updated these test cases to OAS 3.1 since this new enum behavior doesn't appear in 2.0

File: packages/swagger-ts/mocks/enums_2.0.yaml [hunk 4]
```diff
@@ -0,0 +1,23 @@
+definitions:
```
Comment (aburgel) [inline packages/swagger-ts/mocks/enums_2.0.yaml:1]: I left this as swagger 2.0 because I wasn't sure if it was valid 3.1

**Comment by stijnvanhulle** [comment]
@all-contributors add @aburgel for development

**Comment by stijnvanhulle** [comment]
https://github.com/all-contributors add @aburgel for code

**Comment by stijnvanhulle** [comment]
@all-contributors add @aburgel for code
